version: "3.8"

services:
  prom-server:
   image: prom/prometheus
   container_name: prometheus
   ports:
     - 9090:9090
   volumes:
     - ./prometheus-config.yml:/etc/prometheus/prometheus.ymal
  grafana:
   image: grafana/grafana-oss
   container_name: grafana
   ports:
     - 3000:3000
   restart: always