global:
  scrape_interval: 4s # scrape the data after every 4 seconds

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.1.2:8000"] # from this local-host/ourIPaddress:port

